Repository deveBrice/community-platform-JOB, pull requests merged in 2020-03, with the labels that each got.

#123 Fixed content state
  src/Controller/ContentController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Content.php
  src/Migrations/Version20200227150455.php
  src/Migrations/Version20200228095550.php
Labels: bug, frontoffice

#124 @WIP - setup php cs fixer with travis
  .travis.yml
  Dockerfile
  tests/Sample.after
  tests/Sample.php
Labels: CI, dev

#125 Initialized README.md
  README.md
Labels: dev

#126 Feature/added front content index
  public/css/content_index.css
  src/Controller/ContentController.php
  templates/content/index.html.twig
Labels: frontoffice

#129 Feature/added front navbar
  public/css/content_index.css
  public/css/navbar.css
  public/img/community_banner.jpg
  src/Controller/ContentController.php
  templates/content/index.html.twig
  templates/navbar.html.twig
Labels: frontoffice

#132 Feature/added front content create
  public/css/content_index.css
  public/css/navbar.css
  public/css/new-content.css
  public/img/imageonline-co-whitebackgroundremoved.png
  public/img/pencil-icon.png
  src/Form/ContentType.php
  templates/content/_form.html.twig
  templates/content/index.html.twig
  templates/content/new.html.twig
  templates/navbar.html.twig
Labels: frontoffice

#133 Feature/added front show content
  public/css/content_index.css
  public/css/navbar.css
  public/css/show_content.css
  templates/content/_delete_form.html.twig
  templates/content/show.html.twig
Labels: frontoffice

#136 Feature/added front edit content
  public/css/edit_content.css
  src/Controller/ContentController.php
  src/Form/ContentType.php
  templates/content/_form.html.twig
  templates/content/edit.html.twig
Labels: frontoffice

#138 remove whitelines in the files review
  templates/review/index.html.twig
Labels: frontoffice

#140 added front for published content list
  public/css/content_index.css
  templates/home.html.twig
  templates/publisher/index.html.twig
Labels: frontoffice

#141 added front for review content list
  public/css/content_index.css
  src/Controller/PublisherController.php
  templates/content/index.html.twig
  templates/publisher/index.html.twig
  templates/review/index.html.twig
Labels: frontoffice

#142 Fixed admin
  config/packages/admin/comments.yaml
  config/packages/admin/contents_to_publish.yaml
  config/packages/admin/contents_to_review.yaml
  config/packages/admin/menu.yaml
  templates/navbar.html.twig
Labels: admin
