Repository deveBrice/community-platform-JOB, pull requests merged in 2020-02, with the labels that each got.

#108 Setup php composer workflow (CI)
  .github/workflows/php.yml
  composer.json
  composer.lock
  config/bundles.php
  config/packages/sensio_framework_extra.yaml
  symfony.lock
Labels: CI

#113 createdCrudContent
  src/Controller/ContentController.php
  src/Form/ContentType.php
  src/Migrations/Version20200225141943.php
  templates/content/_delete_form.html.twig
  templates/content/_form.html.twig
  templates/content/edit.html.twig
  templates/content/index.html.twig
  templates/content/new.html.twig
  templates/content/show.html.twig
Labels: frontoffice

#115 Added front style authentication
  composer.json
  composer.lock
  public/css/login.css
  public/img/imageonline-co-whitebackgroundremoved.png
  public/img/user_icon.png
  src/Form/LoginType.php
  symfony.lock
  templates/login.html.twig
Labels: frontoffice

#114 Backoffice - Admin - Added CRUD Users
  composer.json
  composer.lock
  config/bundles.php
  config/packages/admin/menu.yaml
  config/packages/admin/users.yaml
  config/packages/easy_admin.yaml
  config/packages/security.yaml
  config/packages/translation.yaml
  config/routes/easy_admin.yaml
  src/Entity/User.php
  src/Migrations/Version20200226103512.php
  src/Security/AccessDeniedHandler.php
  symfony.lock
  translations/.gitignore
Labels: admin, backoffice

#116 Added fullname definition in constructor
  src/Entity/User.php
Labels: bug

#117 updateEntityContent
  src/Entity/Content.php
  src/Migrations/Version20200227112206.php
  src/Migrations/Version20200228092051.php
Labels: bug

#120 bugfixentity
  src/Entity/Content.php
  src/Form/ContentType.php
Labels: bug

#122 updateContentListAndNavBarLink
  src/Controller/ContentController.php
  src/Entity/User.php
  src/Form/ContentType.php
  templates/content/index.html.twig
  templates/navbar.html.twig
Labels: frontoffice

#121 Gathered current fixtures in Appfixtures
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Migrations/Version20200227150455.php
Labels: dev
